@REM This batch file has been generated by the IAR Embedded Workbench
@REM C-SPY Debugger, as an aid to preparing a command line for running
@REM the cspybat command line utility using the appropriate settings.
@REM
@REM You can launch cspybat by typing the name of this batch file followed
@REM by the name of the debug file (usually an ELF/DWARF or UBROF file).
@REM Note that this file is generated every time a new debug session
@REM is initialized, so you may want to move or rename the file before
@REM making changes.
@REM 


"C:\Program Files (x86)\IAR Systems\Embedded Workbench 6.0\common\bin\cspybat" "C:\Program Files (x86)\IAR Systems\Embedded Workbench 6.0\arm\bin\armproc.dll" "C:\Program Files (x86)\IAR Systems\Embedded Workbench 6.0\arm\bin\armjlink.dll"  %1 --plugin "C:\Program Files (x86)\IAR Systems\Embedded Workbench 6.0\arm\bin\armbat.dll" --macro "F:\Work\KaiYang\branches\zhangy\141\HX\HX_N141_D6752_2REC_FG_70D50P_V2\proj\ARKN141_DEMO\ark1960_DEBUG.mac" --backend -B "--endian=little" "--cpu=Cortex-A5" "--fpu=VFPv4" "--semihosting=none" "--drv_communication=USB0" "--jlink_speed=10000" "--drv_catch_exceptions=0x0b7" 


