//****************************************************************************
//
//	Copyright (C) 2012 ZhuoYongHong
//
//	Author	ZhuoYongHong
//
//	File name: app_menuid.h
//	  菜单资源ID
//
//	Revision history
//
//		2012.09.16	ZhuoYongHong Initial version
//
//****************************************************************************

#ifndef _XM_APP_MENUID_H_
#define _XM_APP_MENUID_H_

#if defined (__cplusplus)
	extern "C"{
#endif

#include <xm_type.h>


// 空资源
#define	AP_NULLID			(DWORD)(-1)

typedef enum {
	// 公共资源
	AP_ID_COMMON_BUTTONBACKGROUND = 0,
	AP_ID_COMMON_BUTTONSPLITLINE,
	AP_ID_COMMON_KEY,
	AP_ID_COMMON_LOCK_32,
	AP_ID_COMMON_PAUSE,
	AP_ID_COMMON_MENUITEMBACKGROUND,
	AP_ID_COMMON_MENUITEMBACKGROUND6,
	AP_ID_COMMON_MENUITEMSPLITLINE,
	AP_ID_COMMON_MENUTITLEBARBACKGROUND,
	AP_ID_COMMON_MENU,
	AP_ID_COMMON_MODE,
	AP_ID_COMMON_OK,
	AP_ID_COMMON_POWER,
	AP_ID_COMMON_SWITCH,
	AP_ID_COMMON_VIDEOTOOLBARBACKGROUND,
	AP_ID_BUTTON_CANCEL,
	AP_ID_BUTTON_MODIFY,
	AP_ID_BUTTON_OK,
	AP_ID_BUTTON_RETURN,
    AP_ID_BUTTON_NEXT,
    AP_ID_BUTTON_LAST,
    AP_ID_BUTTON_BACKBACK,

    AP_ID_MENU_BG,
    AP_ID_MENU_TOP_BAR,
    AP_ID_MENU_BOTTOM_BAR,
    AP_ID_MENU_BOTTOM_BAR_A,
    
    AP_ID_MENU_ICON_DATE,
    AP_ID_MENU_ICON_MOT,
    AP_ID_MENU_ICON_DEC,
    AP_ID_MENU_ICON_COLOR,
    AP_ID_MENU_ICON_REC,
    AP_ID_MENU_ICON_SYS,
    AP_ID_MENU_ICON_HOME,
    AP_ID_MENU_ICON_HOME_ACTIVE,
    AP_ID_MENU_ACTIVE,
    AP_ID_MENU_NORMAL,
    AP_ID_SLIDER_THUMB_N,
    AP_ID_COLOR_RULER,
    
    AP_ID_TXT_DATE,
    AP_ID_TXT_MOT,
    AP_ID_TXT_DEC,
    AP_ID_TXT_COLOR,
    AP_ID_TXT_REC,
    AP_ID_TXT_SYS,

    AP_ID_DATE_MENU_ICON_N,
    AP_ID_DATE_MENU_ICON_A,
    AP_ID_DATE_MENU_ICON_DATE,
    AP_ID_DATE_MENU_ICON_TIME,

    AP_ID_LISTVIEW_ITEM_A,
    AP_ID_LISTVIEW_ITEM_N,
    
    AP_ID_VIDEO_ICON_CYC,
    AP_ID_VIDEO_ICON_WATER,
    AP_ID_VIDEO_ICON_PARKING_LINE,
    AP_ID_VIDEO_ICON_PARKING_DELAY,
    AP_ID_VIDEO_CYC_VAL_BG,

    AP_ID_VIDEO_CLOSE,
    AP_ID_VIDEO_CYC_1MIN,
    AP_ID_VIDEO_CYC_3MIN,
    AP_ID_VIDEO_CYC_5MIN,
    AP_ID_VIDEO_CYC_10MIN,
    
    AP_ID_VIDEO_TXT_CYC,
    AP_ID_VIDEO_TXT_WATER,
    AP_ID_VIDEO_TXT_PARKING_LINE,
    AP_ID_VIDEO_TXT_PARKING_DELAY,

    AP_ID_MOT_ICON_MOT,
    AP_ID_MOT_TXT_MOT,
    
    AP_ID_LISTVIEW_SWITCH_ON,
    AP_ID_LISTVIEW_SWITCH_OFF,

    AP_ID_SYS_MENU_ITEM_A,
    AP_ID_SYS_MENU_ITEM_N,

    AP_ID_SYS_MENU_TXT_LCD_PRO,
    AP_ID_SYS_MENU_TXT_FLIP,
    AP_ID_SYS_MENU_TXT_LANG,
    AP_ID_SYS_MENU_TXT_RESET,
    AP_ID_SYS_MENU_TXT_MIRROR_CH1,
    AP_ID_SYS_MENU_TXT_MIRROR_CH2,
    AP_ID_SYS_MENU_TXT_SD_FORMAT,
    AP_ID_SYS_MENU_TXT_VERSION,
    
    AP_ID_SYS_MENU_TXT_FLIP_NOR,
    AP_ID_SYS_MENU_TXT_FLIP_180,
    AP_ID_SYS_MENU_TXT_FLIP_V,
    AP_ID_SYS_MENU_TXT_FLIP_H,

    AP_ID_SYS_MENU_TXT_LANG_CHT,
    AP_ID_SYS_MENU_TXT_LANG_CHS,
    AP_ID_SYS_MENU_TXT_LANG_EN,
    
    AP_ID_SYS_MENU_SWITCH_ON,
    AP_ID_SYS_MENU_SWITCH_OFF,

    AP_ID_SYS_ALERT_OK,
    AP_ID_SYS_ALERT_CANCEL,
    AP_ID_SYS_ALERT_BTN_A,

    AP_ID_SYS_MENU_TITLE_FORMATE,
    AP_ID_SYS_MENU_TITLE_RESET,
    AP_ID_SYS_MENU_TITLE_VERSION,
#if 0
    AP_ID_MENU_DESK_DATA_RECT,
    AP_ID_MENU_DESK_DATA_BG,
    AP_ID_MENU_DESK_TIME_BG,
    
    AP_ID_MENU_DESK_ITEMS_RECT,
    AP_ID_MENU_DESK_ICON_HOME,
    AP_ID_MENU_DESK_ICON_REC,
    AP_ID_MENU_DESK_ICON_DEC,
    AP_ID_MENU_DESK_ICON_SETTINGS,
    AP_ID_MENU_DESK_ICON_LANG,
#endif
//    AP_ID_MENU_TEST,
//	AP_ID_MENU_BG,	// "设置"资源ID定义
	AP_ID_SETTING_CLOSE,
	AP_ID_SETTING_ICON,
	AP_ID_SETTING_KEY,
	AP_ID_SETTING_LANG,
	AP_ID_SETTING_LCD,
	AP_ID_SETTING_MIC,
	AP_ID_SETTING_OPEN,
	AP_ID_SETTING_RECORD,
	AP_ID_SETTING_TIME,
	AP_ID_SETTING_DAYNIGHT,
	AP_ID_SETTING_TITLE,
	//color
	AP_ID_SETTING_PICTURE,
	AP_ID_SETTING_COLOR,
	AP_ID_SETTING_BRIGHT,
	AP_ID_SETTING_CONTRAST,	
	AP_ID_SETTING_SATURATION,
	AP_ID_SETTING_RESET,

	AP_ID_SETTING_COLOR_A,
	AP_ID_SETTING_BRIGHT_A,
	AP_ID_SETTING_CONTRAST_A,	
	AP_ID_SETTING_SATURATION_A,
	
	//function
	AP_ID_SETTING_FUNCTION,
	AP_ID_SETTING_ROTATE,
	AP_ID_SETTING_AUTO_BIGHTNESS,
	AP_ID_SETTING_BLUE,
	//guide delay
    AP_ID_SETTING_DELAY,
    AP_ID_SETTING_CAMERA1,
    AP_ID_SETTING_CAMERA2,
    AP_ID_SETTING_CAMERA3,
    AP_ID_SETTING_CAMERA4,
    AP_ID_SETTING_SECOND,
    //GUIde
    AP_ID_SETTING_GUIDE,
    AP_ID_SETTING_GUIDE_1,
    AP_ID_SETTING_GUIDE_2,
    AP_ID_SETTING_GUIDE_3,
    AP_ID_SETTING_GUIDE_4,
    //factory
    AP_ID_SETTING_FACTORY,
    AP_ID_SETTING_CARBACK,
    AP_ID_SETTING_POWERON,
    AP_ID_SETTING_AHDCHANNELNUM,
    AP_ID_SETTING_KEYBOARD,
    AP_ID_SETTING_VOLONOFF,
    AP_ID_SETTING_LOGOENABLE,
    AP_ID_SETTING_AUTODIM,
    AP_ID_SETTING_MIDDLE,
    AP_ID_SETTING_VCOM,
    AP_ID_SETTING_EXIT,
    AP_ID_SETTING_TESTKEY,
    AP_ID_SETTING_VERSION,
    AP_ID_SETTING_730,
    AP_ID_SETTING_1CH,
    AP_ID_SETTING_2CH,
    AP_ID_SETTING_3CH,
    AP_ID_SETTING_4CH,
    AP_ID_SETTING_ON,
    AP_ID_SETTING_MOMERY,
    AP_ID_SETTING_OFF,
    AP_ID_SETTING_Show,
    AP_ID_SETTING_Show_Select_0,
    AP_ID_SETTING_Show_Select_1,
    AP_ID_SETTING_Show_Select_2,
    AP_ID_SETTING_Show_Select_Double,
    AP_ID_SETTING_Show_Select_Left,
    AP_ID_SETTING_Show_Select_Right,
    AP_ID_SETTING_Show_Select_Up,
    AP_ID_SETTING_Show_Select_Vert,
    //VOL
    AP_ID_SETTING_SELECT,
    AP_ID_SETTING_NO_SELECT,
    AP_ID_VOL_SELECT,
    AP_ID_V1V2_3S,
    AP_ID_SETTING_SLEEP,
	//singed
	AP_ID_SETTING_SINGED_BLUE,
	AP_ID_SETTING_SINGED_BLACK,
	// "录音"资源ID定义
	AP_ID_SETTING_MIC_TITLE,
	// "语音提醒"资源ID定义
	AP_ID_SETTING_VOICE_TITLE,
	// "LCD关闭"资源ID定义
	AP_ID_SETTING_LCD_TITLE,
	AP_ID_SETTING_LCD_NEVERCLOSE,
	AP_ID_SETTING_LCD_S20,
	AP_ID_SETTING_LCD_S30,
	AP_ID_SETTING_LCD_S40,
	AP_ID_SETTING_LCD_S60,
	AP_ID_SETTING_LCD_S120,
	AP_ID_SETTING_LCD_S300,
	// "按键音"
	AP_ID_SETTING_KEY_TITLE,
	// "语言"
	AP_ID_SETTING_LANG_TITLE,
	// "时间设置"
	AP_ID_SETTING_TIME_TITLE,
	AP_ID_BUTTON_TIME_NEXT,

	// “卡信息标题
	AP_ID_CARD_INFO_LOWSPACE,				// “卡容量低”提示信息
	AP_ID_CARD_INFO_LOWSPEED,				// “卡读写速度低”提示信息
	AP_ID_CARD_INFO_LOWPREFORMANCE,		// "SD卡读写效率较低，可能需要重新格式化"
	AP_ID_CARD_INFO_RECYCLE_CONSUMED,	// "锁定的录像文件已满，无法循环录像，请删除文件或重新格式化"

	AP_ID_CARD_INFO_FORMAT_INITIAL,		// “开始格式化操作”提示信息
	AP_ID_CARD_INFO_FORMATCONFIRM,		// “卡格式化确认”提示信息
	AP_ID_CARD_INFO_FORMATTING,			// “正在格式化中”提示信息
	AP_ID_CARD_INFO_FORMATSUCCESS,		// “卡格式化成功”提示信息
	AP_ID_CARD_INFO_FORMATFAILURE,		// “卡格式化失败”提示信息

	AP_ID_CARD_INFO_SYSUPDATE_INITIAL,	// "系统升级开始"提示信息
	AP_ID_CARD_INFO_SYSUPDATE_CONFIRM,	// "系统升级确认"提示信息
	AP_ID_CARD_INFO_SYSUPDATE_WORKING,	// "系统升级进行中"提示信息
	AP_ID_CARD_INFO_SYSUPDATE_SUCCESS,	// "系统升级成功"提示信息
	AP_ID_CARD_INFO_SYSUPDATE_FAILURE,	// "系统升级失败"提示信息
	AP_ID_CARD_INFO_SYSUPDATE_REBOOT,	// "重启系统"按钮, OK按钮
	AP_ID_CARD_INFO_SYSUPDATE_INFO_FINISH,	// "系统升级已完成, 10秒后自动重启"提示信息

	AP_ID_CARD_INFO_RESTORE_INITIAL,		// "恢复出厂设置开始"提示信息
	AP_ID_CARD_INFO_RESTORE_CONFIRM,		// "恢复出厂设置确认"提示信息
	AP_ID_CARD_INFO_RESTORE_WORKING,		// "恢复出厂设置进行中"提示信息
	AP_ID_CARD_INFO_RESTORE_SUCCESS,		// "恢复出厂设置成功"提示信息
	AP_ID_CARD_INFO_RESTORE_FAILURE,		// "恢复出厂设置失败"提示信息

	AP_ID_CARD_ICON_SDCARD,					// SDCARD图标 
	AP_ID_CARD_MESSAGE_CARD_DETECT,			// “SD卡正在准备中” 
	AP_ID_CARD_MESSAGE_CARD_INSERT,			// “数据卡已插入”
	AP_ID_CARD_MESSAGE_CARD_WITHDRAW,		// “数据卡已拔出”
	AP_ID_CARD_MESSAGE_CARD_FSERROR,			// “SD卡文件系统已损坏, 需要重新格式化”
	AP_ID_CARD_MESSAGE_CARD_VERIFYFAILED,	// “文件读写校验失败，数据卡已损坏”
	AP_ID_CARD_MESSAGE_CARD_INVALID,			// “SD卡无法识别，请重新插入或更换新卡”
	AP_ID_CARD_MESSAGE_CARD_DISK_FULL,		// “SD卡已写满，需要重新格式化”

	// 摄像头信息
	AP_ID_CAMERA_INFO_CAMERADISCONNECT,		//	"硬件异常，无法连接到摄像头"
	AP_ID_CAMERA_ICON_CAMERADISCONNECT,		//	Camera图标

	// 电池信息
	AP_ID_MAINBATTERY_INFO_WORST,				// 电池电量已耗尽，系统即将关机。
	AP_ID_BACKUPBATTERY_INFO_WORST,			//	备份电池电力耗尽，请更换
	AP_ID_BATTERY_ICON,							// 电池ICON图标

	// "录像设置"
	AP_ID_VIDEOSETTING_TITLE,						// “录像”标题
	AP_ID_VIDEOSETTING_BUTTON_WATERMARK,		//	"水印"按钮标题
	AP_ID_VIDEOSETTING_BUTTON_SYSTEM,			//	"系统"按钮标题
	AP_ID_VIDEOSETTING_VOICEPROMPTS,				// "语音提示"
	//AP_ID_VIDEOSETTING_RECORDTIMEALARM,			// "可录时间报警"
	AP_ID_VIDEOSETTING_VIDEOSEGMENTSIZE,		// "录像分段时间"
	AP_ID_VIDEOSETTING_COLLISIONSENSITIVITY,	// “碰撞灵敏度”
	AP_ID_VIDEOSETTING_TIMEWATERMARK,			// "时间水印"
	AP_ID_VIDEOSETTING_RCDDELAY,					// “记录延时”
	AP_ID_VIDEOSETTING_URGENTRECORDTIME,		// "紧急录像时间"
	AP_ID_VIDEOSETTING_RECORDRESOLUTION,		// "录像分辨率"
	AP_ID_VIDEOSETTING_EXPOSURECOMPENSATION,		// "曝光补偿"
    AP_ID_VIDEOSETTING_LIGHTFREP,		// "光源频率"
	AP_ID_VIDEOSETTING_VOICEPROMPTS_TITLE,

	AP_ID_VIDEOSETTING_RECORDTIMEALARM_TITLE,
	AP_ID_VIDEOSETTING_RECORDTIMEALARM_MIN5,
	AP_ID_VIDEOSETTING_RECORDTIMEALARM_MIN10,
	AP_ID_VIDEOSETTING_RECORDTIMEALARM_MIN15,
	AP_ID_VIDEOSETTING_RECORDTIMEALARM_MIN20,
	AP_ID_VIDEOSETTING_RECORDTIMEALARM_MIN30,
	AP_ID_VIDEOSETTING_RECORDTIMEALARM_HOUR1,
	AP_ID_VIDEOSETTING_RECORDTIMEALARM_HOUR2,
	
	// 录像分段时间
	AP_ID_VIDEOSETTING_VIDEOSEGMENTSIZE_TITLE,
	AP_ID_VIDEOSETTING_VIDEOSEGMENTSIZE_2_MINUTE,		// 2分钟
	AP_ID_VIDEOSETTING_VIDEOSEGMENTSIZE_3_MINUTE,		// 3分钟
	AP_ID_VIDEOSETTING_VIDEOSEGMENTSIZE_5_MINUTE,		// 5分钟

	// 碰撞灵敏度
	AP_ID_VIDEOSETTING_COLLISIONSENSITIVITY_TITLE,
	AP_ID_VIDEOSETTING_COLLISIONSENSITIVITY_LOW,
	AP_ID_VIDEOSETTING_COLLISIONSENSITIVITY_MEDIUM,
	AP_ID_VIDEOSETTING_COLLISIONSENSITIVITY_HIGH,

	AP_ID_VIDEOSETTING_TIMEWATERMARK_TITLE,
	
	// “记录延时”
	AP_ID_VIDEOSETTING_RCDDELAY_TITLE,
	AP_ID_VIDEOSETTING_RCDDELAY_S0,
	AP_ID_VIDEOSETTING_RCDDELAY_S3,
	AP_ID_VIDEOSETTING_RCDDELAY_S5,
	AP_ID_VIDEOSETTING_RCDDELAY_S10,
	AP_ID_VIDEOSETTING_RCDDELAY_S15,
	AP_ID_VIDEOSETTING_RCDDELAY_S20,
	AP_ID_VIDEOSETTING_RCDDELAY_S30,
	AP_ID_VIDEOSETTING_URGENTRECORD_TITLE,

	// 视频记录分辨率
	AP_ID_VIDEOSETTING_RECORDRESOLUTION_TITLE,
	AP_ID_VIDEOSETTING_RECORDRESOLUTION_1080P_30,		// 1080P 30
	AP_ID_VIDEOSETTING_RECORDRESOLUTION_1080P_60,		// 1080P 60
	AP_ID_VIDEOSETTING_RECORDRESOLUTION_720P_30,			// 720P 30
	AP_ID_VIDEOSETTING_RECORDRESOLUTION_720P_60,			// 720P 60
	
	// 视频曝光补偿
	AP_ID_VIDEOSETTING_EXPOSURECOMPENSATION_TITLE,
	AP_ID_VIDEOSETTING_EXPOSURECOMPENSATION_NEGA_2,		// -2
	AP_ID_VIDEOSETTING_EXPOSURECOMPENSATION_NEGA_1,		// -1
	AP_ID_VIDEOSETTING_EXPOSURECOMPENSATION_POSI_0,		// 0
	AP_ID_VIDEOSETTING_EXPOSURECOMPENSATION_POSI_1,		// +1
	AP_ID_VIDEOSETTING_EXPOSURECOMPENSATION_POSI_2,		// +2
	
	// 视频光源频率
	AP_ID_VIDEOSETTING_LIGHTFREQ_TITLE,
	AP_ID_VIDEOSETTING_LIGHTFREQ_50HZ,		//50HZ
	AP_ID_VIDEOSETTING_LIGHTFREQ_60HZ,		// 60HZ
	AP_ID_VIDEOSETTING_LIGHTFREQ_CLOSE,		// 关
	
	//停车监控标题
	AP_ID_VIDEOSETTING_PARKMONITOR_TITLE,

	// “水印设置”
	AP_ID_WATERMARKSETTING_TITLE,					// “水印设置”标题
	AP_ID_WATERMARKSETTING_TIME,					// 时间戳水印
	AP_ID_WATERMARKSETTING_GPS,					// GPS水印
	AP_ID_WATERMARKSETTING_LOGO,					// 标志水印
	AP_ID_WATERMARKSETTING_LOGO_LOAD,			// 标志水印载入
	AP_ID_WATERMARKSETTING_LOGO_LOGOPNGLOAD_TITLE,	// “标志水印载入”标题

	// “语音提醒”
	AP_ID_VOICEASSISTANT_TITLE,					// 语音提醒设置标题
	AP_ID_VOICEASSISTANT_BATTERY_ALARM,			// 电池电量语音提示
	AP_ID_VOICEASSISTANT_CARD_STATUS_ALARM,
	AP_ID_VOICEASSISTANT_DRIVE_ALARM,
	AP_ID_VOICEASSISTANT_MIC_STATE_ALARM,
	AP_ID_VOICEASSISTANT_NAVIGATE_STATUS_ALARM,
	AP_ID_VOICEASSISTANT_REC_STATE_ALARM,
	AP_ID_VOICEASSISTANT_STORAGE_ALARM,
	AP_ID_VOICEASSISTANT_URGENT_RECORD_ALARM,

	// “系统设置”
	AP_ID_SYSTEMSETTING_TITLE,						// “系统”标题
	AP_ID_SYSTEMSETTING_BUTTON_SETTING,			// “设置”按钮标题
	AP_ID_SYSTEMSETTING_DEMOMODE,					// “演示模式”
	AP_ID_SYSTEMSETTING_FORMAT,					// “格式化”
	AP_ID_SYSTEMSETTING_RESTORESETTING,			// “恢复出厂设置”
	AP_ID_SYSTEMSETTING_RESTORESETTING_TITLE,
	AP_ID_SYSTEMSETTING_RESTORESETTING_INFO,
	AP_ID_SYSTEMSETTING_SYSTEMUPDATE,			// “系统升级”
	AP_ID_SYSTEMSETTING_SOFTWAREVERSION,		// “软件版本”
	AP_ID_SYSTEMSETTING_SDCARDVOLUME,			// "SDCARD容量"
	AP_ID_SYSTEMSETTING_SDCARDVOLUME_TITLE,	// 
	AP_ID_SYSTEMSETTING_VERSION_TITLE,			// “版本信息标题”
	AP_ID_SYSEEMSETTING_FORMAT_TITLE,			// "格式化的窗口标题"
	AP_ID_SYSTEMSETTING_UPDATE_TITLE,			// 系统升级的视窗标题
	AP_ID_SYSTEMSETTING_UPDATE_CURVER_INDICATOR,
	AP_ID_SYSTEMSETTING_UPDATE_NEWVER_INDICATOR,
	AP_ID_SYSTEMSETTING_UPDATE_FILE_ABNORMAL,
	
	// “录像”
	AP_ID_VIDEO_TITLE_CIRCULARVIDEO,				// "循环录像"标题
	AP_ID_VIDEO_TITLE_PROTECTEDVIDEO,			// "保护录像"标题
	AP_ID_VIDEO_TITLE_COMMAND,						// "视频命令"标题
	AP_ID_VIDEO_CIRCULARVIDEO,						// "循环录像"按钮
	AP_ID_VIDEO_COMMAND,								// "命令"
	AP_ID_VIDEO_LOCKVIDEO,							// "锁定"
	AP_ID_VIDEO_PLAY,									// "播放"
	AP_ID_VIDEO_PROTECTEDVIDEO,					// “保护录像”
	AP_ID_VIDEO_UNLOCKVIDEO,						// “解锁”
	AP_ID_VIDEO_BUTTON_VIDEO,						// "录像"按钮
	AP_ID_VIDEO_TITLE_VIDEO,						// "录像"标题
	AP_ID_VIDEO_BUTTON_ALBUM,						// "照片"按钮
	AP_ID_VIDEO_TITLE_ALBUM,						// "照片"标题
	AP_ID_VIDEO_BUTTON_VIEW,						// "查看"
	AP_ID_VIDEO_BUTTON_DELETE_ONE,				// "删除"
	AP_ID_VIDEO_BUTTON_DELETE_ALL,				// "删除全部"
	AP_ID_VIDEO_INFO_TO_DELETE_PHOTO,			// "确实要把此照片删除吗?"
	AP_ID_VIDEO_INFO_TO_DELETE_ALL_PHOTO,		// "确实要删除全部照片吗?"
	AP_ID_VIDEO_BUTTON_DELETE_YES,				// "删除"
	AP_ID_VIDEO_BUTTON_CANCEL_NO,					// "取消"
	AP_ID_VIDEO_BUTTON_LOCK_DELETE,				//	"锁定/删除"
	AP_ID_VIDEO_BUTTON_UNLOCK_DELETE,			// "解锁/删除"
	AP_ID_VIDEO_BUTTON_RECYCLE,					// "回收站"按钮
	AP_ID_VIDEO_BUTTON_PAUSE,						// "暂停"按钮
	AP_ID_VIDEO_BUTTON_PLAY,						// "播放"按钮

	// "录像回放视窗"
	AP_ID_VIDEO_VIEW_DIALOG_BUTTON_CANCEL,		// "取消"按钮
	AP_ID_VIDEO_VIEW_DIALOG_BUTTON_DELETE,		// "删除"按钮
	AP_ID_VIDEO_VIEW_DIALOG_BUTTON_LOCK,		// "锁定视频"按钮
	AP_ID_VIDEO_VIEW_DIALOG_BUTTON_UNLOCK,		// "解锁视频"按钮
	AP_ID_VIDEO_VIEW_DIALOG_INFO_SELECT,		// "选择将要完成的命令"
	AP_ID_VIDEO_VIEW_BUTTON_LOCK,					// "锁定"按钮
	AP_ID_VIDEO_VIEW_BUTTON_UNLOCK,				// "解锁"按钮
	AP_ID_VIDEO_INFO_PHOTO_DAMAGE,				// "该视频可能已损坏, 或无法播放"
	
	AP_ID_VIDEO_VIEW_SCAN_VIDEO_FILE,			// "正在扫描视频文件, 请稍候"

	// "回收站"
	AP_ID_RECYCLE_BUTTON_RESTORE_ONE,			// "还原"按钮
	AP_ID_RECYCLE_BUTTON_RESTORE_ALL,			// "还原全部"按钮
	AP_ID_RECYCLE_TITLE,								// "回收站"标题
	AP_ID_RECYCLE_ICON_VIDEO_24,					// "视频"文件图标
	AP_ID_RECYCLE_ICON_PHOTO_24,					// "照片"文件图标
	AP_ID_RECYCLE_INFO_RESTORE_FILE_ERROR,		// "还原该文件出现错误, 未能完成"
	AP_ID_RECYCLE_ICON_CHANNEL_1_16,				// "1" 通道1(前置摄像头)的ICON
	AP_ID_RECYCLE_ICON_CHANNEL_2_16,				// "2" 通道2(后视摄像头)的ICON

	// "照片"
	AP_ID_PHOTO_INFO_PHOTO_DAMAGE,				// "该照片可能已损坏, 或无法显示"

	// “信息视窗”
	AP_ID_MESSAGE_PROMPT_TITLE,					// "提示信息"
	AP_ID_MESSAGE_SUCCESS,					// "提示信息"
	AP_ID_MESSAGE_FAIL,					// "提示信息"

	// “行车记录视窗”
	AP_ID_ALERT_FORMAT_NORMAL,
	AP_ID_ALERT_FORMAT_PRESSED,
	AP_ID_ALERT_CANCEL_NORMAL,
	AP_ID_ALERT_CANCEL_PRESSED,

	// 系统升级对话框
	AP_ID_SYSTEMUPDATE_TITLE,		// 标题
	AP_ID_SYSTEMUPDATE_YES,			// YES
	AP_ID_SYSTEMUPDATE_CANCEL,		// Cancel , 返回取消

	AP_ID_COMMON_RIGHT_ARROW,

	// "语言"
	AP_ID_SETTING_LANG_CHINESE_SIMPLIFIED,
	AP_ID_SETTING_LANG_ENGLISH,
	AP_ID_SETTING_LANG_RUSSIAN,
	AP_ID_SETTING_LANG_CHINESE_TRADITIONAL,
	AP_ID_SETTING_LANG_FRENCH,
	AP_ID_SETTING_LANG_JAPANESE,
	AP_ID_SETTING_LANG_KOREAN,
	AP_ID_SETTING_LANG_GERMAN,

	// "ALERT"资源
	AP_ID_ALERT_BUTTON_NORMAL,
	AP_ID_ALERT_BUTTON_PRESSED,
	AP_ID_ALERT_BUTTON_OK_NORMAL,
	AP_ID_ALERT_BUTTON_OK_PRESSED,
	AP_ID_ALERT_TITLE,

	// ERGENT紧急录像
	AP_ID_URGENT_RECORD_MESSAGE,
	AP_ID_URGENT_RECORD_IMAGE,

	// 铃声、录音音量
	AP_ID_SETTING_VOLUME_SOUND_TITLE_BELL,		// 铃声音量标题
	AP_ID_SETTING_VOLUME_MIC_TITLE_BELL,		// 录音音量标题
	AP_ID_SETTING_VOLUME_SOUND_IMAGE,			// 铃声背景图片(160x160)
	AP_ID_SETTING_VOLUME_MIC_IMAGE,				// MIC背景图片(160x160)
	AP_ID_SETTING_VOLUME_SOUND_IMAGE_SMALL,	// 铃声背景图片(80X80)
	AP_ID_SETTING_VOLUME_MIC_IMAGE_SMALL,		// MIC背景图片(80X80)
	AP_ID_SETTING_VOLUME_ADJUST,					// 音量调节

	// USB连接、断开
	AP_ID_USB_CONNECT_CHARGE_TITLE,				// USB正在充电标题
	AP_ID_USB_CONNECT_CHARGE_IMAGE,				// USB正在充电图片
	AP_ID_USB_CONNECT_UDISK_TITLE,				// U盘正在使用标题
	AP_ID_USB_CONNECT_UDISK_IMAGE,				// U盘正在使用图片
	AP_ID_USB_DISCONNECT_TITLE,					// USB已断开
	AP_ID_USB_DISCONNECT_IMAGE,
	
	// GPSBD
	AP_ID_GPSBD_ICON,									// GPSBD ICON图标
	AP_ID_GPSBD_DISCONNECT,							// GPSBD已断开
	AP_ID_GPSBD_CONNECT_LOCATE_OK,				// GPSBD已定位

	// 测速雷达报警 radar alarm
	AP_ID_RADAR_ALARM_TITLE,						// 前方有测速雷达

	// 疲劳驾驶
	AP_ID_DRIVING_LONGTIME_WARNING,				// 疲劳驾驶预警
	AP_ID_DRIVING_LONGTIME_ALARM,					// 疲劳驾驶警报
	AP_ID_DRIVING_LONGTIME_FLAG,					// 疲劳驾驶标志

	// 循环录像报警
	AP_ID_RECYCLEVIDEO_ALARM_TITLE,				// 循环录像时间低于设定值
	AP_ID_RECYCLEVIDEO_SDCARD_SPACE,				// 卡空间容量
	AP_ID_RECYCLEVIDEO_RECYCLE_SPACE,			// 循环录像
	AP_ID_RECYCLEVIDEO_LOCKED_SPACE,				// 锁定视频
	AP_ID_RECYCLEVIDEO_OTHERS_SPACE,				// 其他空间
	/*
	AP_ID_MAIN_REPLAY_DOWN,
	AP_ID_MAIN_REPLAY_UP,
	AP_ID_MAIN_SET_DOWN,
	AP_ID_MAIN_SET_UP,
	AP_ID_MAIN_VIDEO_DOWN,
	AP_ID_MAIN_VIDEO_UP,
	AP_ID_MAIN_PHOTO_DOWN,
	AP_ID_MAIN_PHOTO_UP,
	*/
	AP_ID_DATESETTING_UP,
	AP_ID_DATESETTING_DOWN,
	AP_ID_PHOTO,
	AP_ID_MIC_ON,
	AP_ID_MIC_OFF,
	AP_ID_VIDEOSETTING_MONITOR,                           // 停车监控
	AP_ID_VIDEO_ICON_VIDEOSTOP,	  						//停止录像图标
	AP_ID_VIDEO_MESSAGE_VIDEO_STOP,					  // “请停止录像” 
	AP_ID_DATETIME_CHAR_COLON,

    AP_ID_VIDEO_BUTTON_CH,
	AP_ID_VIDEO_BUTTON_CH1,
	AP_ID_VIDEO_BUTTON_CH2,
	AP_ID_VIDEO_BUTTON_TYPE,
	AP_ID_VIDEO_BUTTON_PAGE,
	AP_ID_VIDEO_BUTTON_REPLAYMENU,
	AP_ID_VIDEO_BUTTON_PLAY_ICON,
	AP_ID_VIDEO_INFO_TO_DELETE_ONE_VIDEO,
	AP_ID_VIDEO_INFO_TO_DELETE_ALL_VIDEO,
	AP_ID_ALERT_BG_PIC,//弹窗背景图片
	AP_ID_ALERT_SD_FORMAT_PIC,//格式化标题
	AP_ID_SD_FORMAT_INITIAL,//是否进行SD卡格式化
	AP_ID_SD_FORMATTING,//正在格式化
	AP_ID_SD_FORMATSUCCESS,//格式化成功
	AP_ID_SD_FORMATFAILURE,//格式化失败
	AP_ID_SD_OK,//确认
	AP_ID_SD_CANCEL,//取消
	AP_ID_SD_BUTTON,//按钮选中
	AP_ID_RESET_TITLE,//恢复默认标题
	AP_ID_RESET_INITIAL,//是否恢复成默认值
	AP_ID_RESET_SUCC,//所有参数被恢复成默认值
	AP_ID_LEFT_ICON,//左向图标
	AP_ID_RIGHT_ICON,//右向图标

	AP_ID_COUNT
} APPMENUID;

#define AP_ID_CCD_ICON		AP_NULLID

#define ICON_WEIGHT			24
#define ICON_HEIGHT			24

// 资源ROM结构
typedef struct _tagAPPROMRES {
	u32_t		rom_offset;			// 资源位于ROM中的偏移
	u32_t		res_length;			// 资源字节大小
} APPROMRES;

// 根据菜单ID获取对应的ROM资源信息
APPROMRES *	AP_AppRes2RomRes (u32_t ResID);

// 获取与按键关联的提示资源
// Key	按键的键值
APPROMRES* AP_AppGetKeyClueRes (u32_t Key);

// 根据菜单ID获取对应的ROM资源偏移
u32_t	AP_AppRes2RomOffset (u32_t MenuID);

#if defined (__cplusplus)
	}
#endif		/* end of __cplusplus */

#endif	// #ifndef _XM_APP_MENUDATA_H_
