#ifndef _XM_VOICE_PROMPTS_ID_H_
#define _XM_VOICE_PROMPTS_ID_H_

#if defined (__cplusplus)
	extern "C"{
#endif

// 系统语音ID定义
enum {
	XM_VOICE_ID_SYSCHECKING = 1,				// 系统已开机，正在自检
	XM_VOICE_ID_INIT_SETTING,					// 系统初次使用，请设置
	XM_VOICE_ID_CARD_INSERT,					// 数据卡已插入
	XM_VOICE_ID_CARD_NOCARD,					// 数据卡不存在，请插入卡
	XM_VOICE_ID_CARD_WRITEPROTECT,			// 数据卡写保护，请移去卡的写保护
	XM_VOICE_ID_CARD_FILESYSTEMERROR,		// 数据卡文件系统异常
	XM_VOICE_ID_CARD_DAMAGE,					// 数据卡已损坏，请更换
	XM_VOICE_ID_CARD_INVALID,					// SD卡无法识别，请重新插入或更换新卡
	XM_VOICE_ID_CARD_FORMAT,					// 请确认数据卡格式化操作
	XM_VOICE_ID_TIMESETTING,					// 请设置系统时间
	XM_VOICE_ID_BACKUPBATTERY,					// 备份电池电力耗尽，请更换
	XM_VOICE_ID_MAINBATTERY_WORST,			// 电池电量已耗尽，系统即将关机。
	XM_VOICE_ID_MIC_OFF,							// 录音已关闭	
	XM_VOICE_ID_MIC_ON,							// 录音已开启
	XM_VOICE_ID_VOICE_PROMPTS_ON,				// 语音提示已开启
	XM_VOICE_ID_VOICE_PROMPTS_OFF,			// 语音提示已关闭
	XM_VOICE_ID_TIMESTAMP_OFF,					// 时间水印已关闭	
	XM_VOICE_ID_TIMESTAMP_ON,					// 时间水印已开启	
	XM_VOICE_ID_NOCARD_DEMO_OPERATIONMODE,	//	无卡/只读演示模式
	XM_VOICE_ID_FORCASTRECORDTIME_LOW,		// 可循环录制时间低于设置值
	XM_VOICE_ID_FORCASTRECORDTIME_TITLE,	// 循环录制时间预计
	XM_VOICE_ID_FORCASTRECORDTIME_WORST,	// 低于20分钟
	XM_VOICE_ID_FORCASTRECORDTIME_20M,		// 20分钟
	XM_VOICE_ID_FORCASTRECORDTIME_30M,		// 30分钟
	XM_VOICE_ID_FORCASTRECORDTIME_40M,		// 40分钟
	XM_VOICE_ID_FORCASTRECORDTIME_50M,		// 50分钟
	XM_VOICE_ID_FORCASTRECORDTIME_1H,		// 1小时
	XM_VOICE_ID_FORCASTRECORDTIME_2H,		// 2小时
	XM_VOICE_ID_FORCASTRECORDTIME_3H,		// 3小时
	XM_VOICE_ID_FORCASTRECORDTIME_4H,		// 4小时
	XM_VOICE_ID_FORCASTRECORDTIME_5H,		// 5小时
	XM_VOICE_ID_FORCASTRECORDTIME_6H,		// 6小时
	XM_VOICE_ID_FORCASTRECORDTIME_7H,		// 7小时
	XM_VOICE_ID_FORCASTRECORDTIME_8H,		// 8小时
	XM_VOICE_ID_FORCASTRECORDTIME_9H,		// 9小时
	XM_VOICE_ID_FORCASTRECORDTIME_10H,		// 10小时
	XM_VOICE_ID_FORCASTRECORDTIME_11H,		// 11小时
	XM_VOICE_ID_FORCASTRECORDTIME_12H,		// 超过12小时
	XM_VOICE_ID_ERGENT_RECORD,					// 紧急录像已启动
	XM_VOICE_ID_ERGENT_RECORD_5M,				// 时间长度5分钟
	XM_VOICE_ID_ERGENT_RECORD_10M,			// 时间长度10分钟
	XM_VOICE_ID_ERGENT_RECORD_15M,			// 时间长度15分钟
	XM_VOICE_ID_ERGENT_RECORD_20M,			// 时间长度20分钟

	XM_VOICE_ID_CAMERA_DISCONNECT,			// 硬件异常，无法连接到摄像头

	XM_VOICE_ID_USB_DISCONNECT,				// USB已拔出
	XM_VOICE_ID_USB_CONNECT_UDISK,			// U盘正在使用
	XM_VOICE_ID_USB_CONNECT_CHARGE,			// USB正在充电

	XM_VOICE_ID_RADAR_ALARM,					// 前方有测速雷达
	XM_VOICE_ID_BEEP_KEYBOARD,					// 按键Beep音

	XM_VOICE_ID_DRIVING_LONGTIME_WARNING,	// 疲劳驾驶(长时间驾驶)预警
	XM_VOICE_ID_DRIVING_LONGTIME_ALARM,		// 疲劳驾驶(长时间驾驶)报警
	
	XM_VOICE_ID_COUNT,

	XM_VOICE_ID_CCD_REAR,						// 后摄像头(与其他语音形成完整句子)
	XM_VOICE_ID_CCD_LEFT,						// 左摄像头(与其他语音形成完整句子)
	XM_VOICE_ID_CCD_RIGHT,						// 右摄像头(与其他语音形成完整句子)
	XM_VOICE_ID_CCD_INNER,						// 内摄像头(与其他语音形成完整句子)
	XM_VOICE_ID_CCD_LOST_CONNECT,				// 未能连接
	XM_VOICE_ID_CCD_CONNECT						// 已连接
};

#if defined (__cplusplus)
	}
#endif		/* end of __cplusplus */

#endif	// _XM_VOICE_PROMPTS_ID_H_
